1.




//2. create your own resume data in json format

var resume = {
    "name" : "manikandan",
    "D.O.B": "23/08/1999",
    "genter": "male",
    "father name": "ranganathan",
    "address" : "4/10a anand college opposite kazhipattur",
    "gmail" : "manikandanr23899@gmail.com",
    "contact" : "9952923693",
    "degree" : "bachelor of computer science",
    "school" : "govt.hr.sec.school",
    "skills" : ["javascript","html","css","mangodb","react.js","express.js","node.js"],
    "languages" : ["tamil","english"],
}
console.log(resume.name)